export const locations = [
  {
    id: "0",
    number: "E-RR",
    building: "10",
    floor: "10",
    name: "エラー",
  },
  {
    id: "10101",
    number: "1-1A",
    building: "1",
    floor: "1",
    name: "エントランス",
  },
  {
    id: "10102",
    number: "1-1B",
    building: "1",
    floor: "1",
    name: "警備員・用務員室",
  },
  {
    id: "10103",
    number: "1-1C",
    building: "1",
    floor: "1",
    name: "相談室・保健室",
  },
  {
    id: "10104",
    number: "1-1D",
    building: "1",
    floor: "1",
    name: "倉庫",
  },
  {
    id: "10105",
    number: "1-1E",
    building: "1",
    floor: "1",
    name: "機械室",
  },
  {
    id: "10106",
    number: "1-1F",
    building: "1",
    floor: "1",
    name: "男子トイレ",
  },
  {
    id: "10107",
    number: "1-1G",
    building: "1",
    floor: "1",
    name: "教員専用トイレ",
  },
  {
    id: "10108",
    number: "1-1H",
    building: "1",
    floor: "1",
    name: "生活指導室",
  },
  {
    id: "10109",
    number: "1-1I",
    building: "1",
    floor: "1",
    name: "永井体育館",
  },
  {
    id: "10110",
    number: "1-1J",
    building: "1",
    floor: "1",
    name: "洗面所",
  },
  {
    id: "10111",
    number: "1-1K",
    building: "1",
    floor: "1",
    name: "器具庫",
  },
  {
    id: "10112",
    number: "1-1L",
    building: "1",
    floor: "1",
    name: "別室",
  },
  {
    id: "10113",
    number: "1-1M",
    building: "1",
    floor: "1",
    name: "事務室・企画管理部",
  },
  {
    id: "10114",
    number: "1-1N",
    building: "1",
    floor: "1",
    name: "応接室1",
  },
  {
    id: "10115",
    number: "1-1O",
    building: "1",
    floor: "1",
    name: "応接室2",
  },
  {
    id: "10201",
    number: "1-2A",
    building: "1",
    floor: "2",
    name: "ロッカー室",
  },
  {
    id: "10202",
    number: "1-2B",
    building: "1",
    floor: "2",
    name: "中会議室1",
  },
  {
    id: "10203",
    number: "1-2C",
    building: "1",
    floor: "2",
    name: "中会議室2",
  },
  {
    id: "10204",
    number: "1-2D",
    building: "1",
    floor: "2",
    name: "校長室",
  },
  {
    id: "10205",
    number: "1-2E",
    building: "1",
    floor: "2",
    name: "中・高職員室",
  },
  {
    id: "10206",
    number: "1-2F",
    building: "1",
    floor: "2",
    name: "教員用男子トイレ",
  },
  {
    id: "10207",
    number: "1-2G",
    building: "1",
    floor: "2",
    name: "倉庫",
  },
  {
    id: "10208",
    number: "1-2H",
    building: "1",
    floor: "2",
    name: "教員用女子トイレ",
  },
  {
    id: "10209",
    number: "1-2I",
    building: "1",
    floor: "2",
    name: "応接室4",
  },
  {
    id: "10210",
    number: "1-2J",
    building: "1",
    floor: "2",
    name: "応接室3",
  },
  {
    id: "10211",
    number: "1-2K",
    building: "1",
    floor: "2",
    name: "ロッカー室",
  },
  {
    id: "10212",
    number: "1-2L",
    building: "1",
    floor: "2",
    name: "印刷室",
  },
  {
    id: "10213",
    number: "1-2M",
    building: "1",
    floor: "2",
    name: "放送室",
  },
  {
    id: "10214",
    number: "1-2N",
    building: "1",
    floor: "2",
    name: "大会議室",
  },
  {
    id: "10215",
    number: "1-2O",
    building: "1",
    floor: "2",
    name: "役員室",
  },
  {
    id: "10216",
    number: "1-2P",
    building: "1",
    floor: "2",
    name: "理事長室",
  },
  {
    id: "10301",
    number: "1-3A",
    building: "1",
    floor: "3",
    name: "中2-7教室",
  },
  {
    id: "10302",
    number: "1-3B",
    building: "1",
    floor: "3",
    name: "中2-6教室",
  },
  {
    id: "10303",
    number: "1-3C",
    building: "1",
    floor: "3",
    name: "中2-5教室",
  },
  {
    id: "10304",
    number: "1-3D",
    building: "1",
    floor: "3",
    name: "中2-4教室",
  },
  {
    id: "10305",
    number: "1-3E",
    building: "1",
    floor: "3",
    name: "中2-3教室",
  },
  {
    id: "10306",
    number: "1-3F",
    building: "1",
    floor: "3",
    name: "中2-2教室",
  },
  {
    id: "10307",
    number: "1-3G",
    building: "1",
    floor: "3",
    name: "中2-1教室",
  },
  {
    id: "10308",
    number: "1-3H",
    building: "1",
    floor: "3",
    name: "英語科研究室",
  },
  {
    id: "10309",
    number: "1-3I",
    building: "1",
    floor: "3",
    name: "選択教室②",
  },
  {
    id: "10310",
    number: "1-3J",
    building: "1",
    floor: "3",
    name: "応接室5",
  },
  {
    id: "10311",
    number: "1-3K",
    building: "1",
    floor: "3",
    name: "英会話教室①",
  },
  {
    id: "10312",
    number: "1-3L",
    building: "1",
    floor: "3",
    name: "英会話教室②",
  },
  {
    id: "10313",
    number: "1-3M",
    building: "1",
    floor: "3",
    name: "男子トイレ",
  },
  {
    id: "10314",
    number: "1-3N",
    building: "1",
    floor: "3",
    name: "選択教室①",
  },
  {
    id: "10315",
    number: "1-3O",
    building: "1",
    floor: "3",
    name: "倉庫",
  },
  {
    id: "10316",
    number: "1-3P",
    building: "1",
    floor: "3",
    name: "数学科研究室",
  },
  {
    id: "10317",
    number: "1-3Q",
    building: "1",
    floor: "3",
    name: "国語科研究室",
  },
  {
    id: "10318",
    number: "1-3R",
    building: "1",
    floor: "3",
    name: "音楽室(1)",
  },
  {
    id: "10401",
    number: "1-4A",
    building: "1",
    floor: "4",
    name: "中1-7教室",
  },
  {
    id: "10402",
    number: "1-4B",
    building: "1",
    floor: "4",
    name: "中1-6教室",
  },
  {
    id: "10403",
    number: "1-4C",
    building: "1",
    floor: "4",
    name: "中1-5教室",
  },
  {
    id: "10404",
    number: "1-4D",
    building: "1",
    floor: "4",
    name: "中1-4教室",
  },
  {
    id: "10405",
    number: "1-4E",
    building: "1",
    floor: "4",
    name: "中1-3教室",
  },
  {
    id: "10406",
    number: "1-4F",
    building: "1",
    floor: "4",
    name: "中1-2教室",
  },
  {
    id: "10407",
    number: "1-4G",
    building: "1",
    floor: "4",
    name: "中1-1教室",
  },
  {
    id: "10408",
    number: "1-4H",
    building: "1",
    floor: "4",
    name: "選択教室③",
  },
  {
    id: "10409",
    number: "1-4I",
    building: "1",
    floor: "4",
    name: "屋上",
  },
  {
    id: "10410",
    number: "1-4J",
    building: "1",
    floor: "4",
    name: "男子トイレ",
  },
  {
    id: "10411",
    number: "1-4K",
    building: "1",
    floor: "4",
    name: "特別教室1",
  },
  {
    id: "10412",
    number: "1-4L",
    building: "1",
    floor: "4",
    name: "特別教室2",
  },
  {
    id: "20101",
    number: "2-1A",
    building: "2",
    floor: "1",
    name: "エントランスホール",
  },
  {
    id: "20102",
    number: "2-1B",
    building: "2",
    floor: "1",
    name: "本郷ギャラリー",
  },
  {
    id: "20103",
    number: "2-1C",
    building: "2",
    floor: "1",
    name: "男女トイレ",
  },
  {
    id: "20104",
    number: "2-1D",
    building: "2",
    floor: "1",
    name: "入試広報室",
  },
  {
    id: "20105",
    number: "2-1E",
    building: "2",
    floor: "1",
    name: "体育倉庫(吹き抜け下)",
  },
  {
    id: "20106",
    number: "2-1F",
    building: "2",
    floor: "1",
    name: "保健体育科",
  },
  {
    id: "20107",
    number: "2-1G",
    building: "2",
    floor: "1",
    name: "ホール",
  },
  {
    id: "20108",
    number: "2-1H",
    building: "2",
    floor: "1",
    name: "男子トイレ(正面左)",
  },
  {
    id: "20109",
    number: "2-1I",
    building: "2",
    floor: "1",
    name: "トレーニングルーム",
  },
  {
    id: "20201",
    number: "2-2A",
    building: "2",
    floor: "2",
    name: "選択教室A",
  },
  {
    id: "20202",
    number: "2-2B",
    building: "2",
    floor: "2",
    name: "選択教室B",
  },
  {
    id: "20203",
    number: "2-2C",
    building: "2",
    floor: "2",
    name: "司書室",
  },
  {
    id: "20204",
    number: "2-2D",
    building: "2",
    floor: "2",
    name: "図書室",
  },
  {
    id: "20205",
    number: "2-2E",
    building: "2",
    floor: "2",
    name: "進路指導室",
  },
  {
    id: "20206",
    number: "2-2F",
    building: "2",
    floor: "2",
    name: "男子トイレ(正面右)",
  },
  {
    id: "20207",
    number: "2-2G",
    building: "2",
    floor: "2",
    name: "ラーニング・コモンズ",
  },
  {
    id: "20208",
    number: "2-2H",
    building: "2",
    floor: "2",
    name: "印刷室",
  },
  {
    id: "20209",
    number: "2-2I",
    building: "2",
    floor: "2",
    name: "男子トイレ",
  },
  {
    id: "20210",
    number: "2-2J",
    building: "2",
    floor: "2",
    name: "女子トイレ",
  },
  {
    id: "20301",
    number: "2-3A",
    building: "2",
    floor: "3",
    name: "選択教室C",
  },
  {
    id: "20302",
    number: "2-3B",
    building: "2",
    floor: "3",
    name: "高3-9･10教室",
  },
  {
    id: "20303",
    number: "2-3C",
    building: "2",
    floor: "3",
    name: "高3-7･8教室",
  },
  {
    id: "20304",
    number: "2-3D",
    building: "2",
    floor: "3",
    name: "高3-6教室",
  },
  {
    id: "20305",
    number: "2-3E",
    building: "2",
    floor: "3",
    name: "高3-5教室",
  },
  {
    id: "20306",
    number: "2-3F",
    building: "2",
    floor: "3",
    name: "高3-3･4教室",
  },
  {
    id: "20307",
    number: "2-3G",
    building: "2",
    floor: "3",
    name: "高3-2教室",
  },
  {
    id: "20308",
    number: "2-3H",
    building: "2",
    floor: "3",
    name: "高3-1教室",
  },
  {
    id: "20309",
    number: "2-3I",
    building: "2",
    floor: "3",
    name: "男子トイレ(正面右)",
  },
  {
    id: "20310",
    number: "2-3J",
    building: "2",
    floor: "3",
    name: "教員控室",
  },
  {
    id: "20311",
    number: "2-3K",
    building: "2",
    floor: "3",
    name: "面談室",
  },
  {
    id: "20312",
    number: "2-3L",
    building: "2",
    floor: "3",
    name: "女子トイレ",
  },
  {
    id: "20313",
    number: "2-3M",
    building: "2",
    floor: "3",
    name: "男子トイレ(正面左)",
  },
  {
    id: "20401",
    number: "2-4A",
    building: "2",
    floor: "4",
    name: "選択教室D",
  },
  {
    id: "20402",
    number: "2-4B",
    building: "2",
    floor: "4",
    name: "高2-9･10教室",
  },
  {
    id: "20403",
    number: "2-4C",
    building: "2",
    floor: "4",
    name: "高2-7･8教室",
  },
  {
    id: "20404",
    number: "2-4D",
    building: "2",
    floor: "4",
    name: "高2-6教室",
  },
  {
    id: "20405",
    number: "2-4E",
    building: "2",
    floor: "4",
    name: "高2-5教室",
  },
  {
    id: "20406",
    number: "2-4F",
    building: "2",
    floor: "4",
    name: "高2-3･4教室",
  },
  {
    id: "20407",
    number: "2-4G",
    building: "2",
    floor: "4",
    name: "高2-2教室",
  },
  {
    id: "20408",
    number: "2-4H",
    building: "2",
    floor: "4",
    name: "高2-1教室",
  },
  {
    id: "20409",
    number: "2-4I",
    building: "2",
    floor: "4",
    name: "男子トイレ(正面右)",
  },
  {
    id: "20410",
    number: "2-4J",
    building: "2",
    floor: "4",
    name: "教員控室",
  },
  {
    id: "20411",
    number: "2-4K",
    building: "2",
    floor: "4",
    name: "面談室",
  },
  {
    id: "20412",
    number: "2-4J",
    building: "2",
    floor: "4",
    name: "男子トイレ(正面左)",
  },
  {
    id: "20413",
    number: "2-4K",
    building: "2",
    floor: "4",
    name: "女子トイレ(正面右)",
  },
  {
    id: "20501",
    number: "2-5A",
    building: "2",
    floor: "5",
    name: "選択教室E",
  },
  {
    id: "20502",
    number: "2-5B",
    building: "2",
    floor: "5",
    name: "高1-7教室",
  },
  {
    id: "20503",
    number: "2-5C",
    building: "2",
    floor: "5",
    name: "高1-6教室",
  },
  {
    id: "20504",
    number: "2-5D",
    building: "2",
    floor: "5",
    name: "高1-5教室",
  },
  {
    id: "20505",
    number: "2-5E",
    building: "2",
    floor: "5",
    name: "高1-4教室",
  },
  {
    id: "20506",
    number: "2-5F",
    building: "2",
    floor: "5",
    name: "高1-3教室",
  },
  {
    id: "20507",
    number: "2-5G",
    building: "2",
    floor: "5",
    name: "高1-2教室",
  },
  {
    id: "20508",
    number: "2-5H",
    building: "2",
    floor: "5",
    name: "高1-1教室",
  },
  {
    id: "20509",
    number: "2-5I",
    building: "2",
    floor: "5",
    name: "男子トイレ(正面右)",
  },
  {
    id: "20510",
    number: "2-5J",
    building: "2",
    floor: "5",
    name: "教員控室",
  },
  {
    id: "20511",
    number: "2-5K",
    building: "2",
    floor: "5",
    name: "面談室",
  },
  {
    id: "20512",
    number: "2-5L",
    building: "2",
    floor: "5",
    name: "男子トイレ(正面左)",
  },
  {
    id: "20601",
    number: "2-6A",
    building: "2",
    floor: "6",
    name: "投球練習場",
  },
  {
    id: "21101",
    number: "2-7A",
    building: "2",
    floor: "7",
    name: "男子トイレ(正面右)",
  },
  {
    id: "21102",
    number: "2-7B",
    building: "2",
    floor: "7",
    name: "女子トイレ(正面右)",
  },
  {
    id: "21103",
    number: "2-7C",
    building: "2",
    floor: "7",
    name: "控室",
  },
  {
    id: "21104",
    number: "2-7D",
    building: "2",
    floor: "7",
    name: "男子トイレ(正面左)",
  },
  {
    id: "21105",
    number: "2-7E",
    building: "2",
    floor: "7",
    name: "女子トイレ(正面左)",
  },
  {
    id: "21106",
    number: "2-7F",
    building: "2",
    floor: "7",
    name: "倉庫",
  },
  {
    id: "21201",
    number: "2-8A",
    building: "2",
    floor: "8",
    name: "書庫",
  },
  {
    id: "21202",
    number: "2-8B",
    building: "2",
    floor: "8",
    name: "機械室",
  },
  {
    id: "21203",
    number: "2-8C",
    building: "2",
    floor: "8",
    name: "多目的室",
  },
  {
    id: "21204",
    number: "2-8D",
    building: "2",
    floor: "8",
    name: "男子トイレ(正面左)",
  },
  {
    id: "21205",
    number: "2-8E",
    building: "2",
    floor: "8",
    name: "女子トイレ(正面左)",
  },
  {
    id: "21206",
    number: "2-8F",
    building: "2",
    floor: "8",
    name: "備蓄倉庫",
  },
  {
    id: "21207",
    number: "2-8G",
    building: "2",
    floor: "8",
    name: "空調機械室",
  },
  {
    id: "21208",
    number: "2-8H",
    building: "2",
    floor: "8",
    name: "講堂",
  },
  {
    id: "30101",
    number: "3-1A",
    building: "3",
    floor: "1",
    name: "生物・地学講義室",
  },
  {
    id: "30102",
    number: "3-1B",
    building: "3",
    floor: "1",
    name: "生物・地学実験室",
  },
  {
    id: "30103",
    number: "3-1C",
    building: "3",
    floor: "1",
    name: "教員用女子トイレ",
  },
  {
    id: "30104",
    number: "3-1D",
    building: "3",
    floor: "1",
    name: "教員用男子トイレ",
  },
  {
    id: "30105",
    number: "3-1E",
    building: "3",
    floor: "1",
    name: "化学講義室",
  },
  {
    id: "30106",
    number: "3-1F",
    building: "3",
    floor: "1",
    name: "化学実験室",
  },
  {
    id: "30201",
    number: "3-2A",
    building: "3",
    floor: "2",
    name: "生徒会室",
  },
  {
    id: "30202",
    number: "3-2B",
    building: "3",
    floor: "2",
    name: "中学理科実験室",
  },
  {
    id: "30203",
    number: "3-2C",
    building: "3",
    floor: "2",
    name: "男子トイレ",
  },
  {
    id: "30204",
    number: "3-2D",
    building: "3",
    floor: "2",
    name: "物理講義室",
  },
  {
    id: "30205",
    number: "3-2E",
    building: "3",
    floor: "2",
    name: "物理実験室",
  },
  {
    id: "30301",
    number: "3-3A",
    building: "3",
    floor: "3",
    name: "中3-7教室",
  },
  {
    id: "30302",
    number: "3-3B",
    building: "3",
    floor: "3",
    name: "中3-6教室",
  },
  {
    id: "30303",
    number: "3-3C",
    building: "3",
    floor: "3",
    name: "中3-5教室",
  },
  {
    id: "30304",
    number: "3-3D",
    building: "3",
    floor: "3",
    name: "中3-4教室",
  },
  {
    id: "30305",
    number: "3-3E",
    building: "3",
    floor: "3",
    name: "中3-3教室",
  },
  {
    id: "30306",
    number: "3-3F",
    building: "3",
    floor: "3",
    name: "中3-2教室",
  },
  {
    id: "30307",
    number: "3-3G",
    building: "3",
    floor: "3",
    name: "中3-1教室",
  },
  {
    id: "30308",
    number: "3-3H",
    building: "3",
    floor: "3",
    name: "男子トイレ",
  },
  {
    id: "40101",
    number: "4-1A",
    building: "4",
    floor: "1",
    name: "小会議室",
  },
  {
    id: "40102",
    number: "4-1B",
    building: "4",
    floor: "1",
    name: "多目的ホール",
  },
  {
    id: "40103",
    number: "4-1C",
    building: "4",
    floor: "1",
    name: "倉庫",
  },
  {
    id: "40104",
    number: "4-1D",
    building: "4",
    floor: "1",
    name: "男子トイレ",
  },
  {
    id: "40201",
    number: "4-2A",
    building: "4",
    floor: "2",
    name: "技術科実習室(1)",
  },
  {
    id: "40202",
    number: "4-2B",
    building: "4",
    floor: "2",
    name: "男子トイレ",
  },
  {
    id: "40203",
    number: "4-2C",
    building: "4",
    floor: "2",
    name: "選択教室G",
  },
  {
    id: "40204",
    number: "4-2D",
    building: "4",
    floor: "2",
    name: "選択教室F",
  },
  {
    id: "40301",
    number: "4-3A",
    building: "4",
    floor: "3",
    name: "工芸室",
  },
  {
    id: "40302",
    number: "4-3B",
    building: "4",
    floor: "3",
    name: "美術室",
  },
  {
    id: "40303",
    number: "4-3C",
    building: "4",
    floor: "3",
    name: "男子トイレ",
  },
  {
    id: "50101",
    number: "5-1A",
    building: "5",
    floor: "1",
    name: "クラブ倉庫",
  },
  {
    id: "50102",
    number: "5-1B",
    building: "5",
    floor: "1",
    name: "倉庫",
  },
  {
    id: "50103",
    number: "5-1C",
    building: "5",
    floor: "1",
    name: "家庭科調理実習室",
  },
  {
    id: "50104",
    number: "5-1D",
    building: "5",
    floor: "1",
    name: "男子トイレ",
  },
  {
    id: "50105",
    number: "5-1E",
    building: "5",
    floor: "1",
    name: "女子トイレ",
  },
  {
    id: "50106",
    number: "5-1F",
    building: "5",
    floor: "1",
    name: "倉庫",
  },
  {
    id: "50107",
    number: "5-1G",
    building: "5",
    floor: "1",
    name: "応接室6",
  },
  {
    id: "50108",
    number: "5-1H",
    building: "5",
    floor: "1",
    name: "技術科実習室(2)",
  },
  {
    id: "50201",
    number: "5-2A",
    building: "5",
    floor: "2",
    name: "柔道場",
  },
  {
    id: "50202",
    number: "5-2B",
    building: "5",
    floor: "2",
    name: "男子トイレ",
  },
  {
    id: "50203",
    number: "5-2C",
    building: "5",
    floor: "2",
    name: "剣道場",
  },
  {
    id: "50301",
    number: "5-3A",
    building: "5",
    floor: "3",
    name: "pc教室(2)",
  },
  {
    id: "50302",
    number: "5-3B",
    building: "5",
    floor: "3",
    name: "pc教室(1)",
  },
  {
    id: "50303",
    number: "5-3C",
    building: "5",
    floor: "3",
    name: "校史編纂室",
  },
  {
    id: "50304",
    number: "5-3D",
    building: "5",
    floor: "3",
    name: "男子トイレ",
  },
  {
    id: "50305",
    number: "5-3E",
    building: "5",
    floor: "3",
    name: "家庭科実習室",
  },
  {
    id: "60101",
    number: "6-1A",
    building: "6",
    floor: "1",
    name: "カフェテリア",
  },
  {
    id: "60102",
    number: "6-1B",
    building: "6",
    floor: "1",
    name: "男子トイレ",
  },
  {
    id: "60103",
    number: "6-1C",
    building: "6",
    floor: "1",
    name: "女子トイレ",
  },
  {
    id: "60201",
    number: "6-2A",
    building: "6",
    floor: "2",
    name: "自習室",
  },
  {
    id: "60301",
    number: "6-3A",
    building: "6",
    floor: "3",
    name: "視聴覚大教室",
  },
  {
    id: "60401",
    number: "6-4A",
    building: "6",
    floor: "4",
    name: "音楽室(2)",
  },
  {
    id: "60402",
    number: "6-4B",
    building: "6",
    floor: "4",
    name: "書道室",
  },
  {
    id: "70101",
    number: "7-1A",
    building: "7",
    floor: "1",
    name: "本部",
  },
  {
    id: "70102",
    number: "7-1B",
    building: "7",
    floor: "1",
    name: "本郷市(1)",
  },
  {
    id: "70103",
    number: "7-1C",
    building: "7",
    floor: "1",
    name: "本郷市(2)",
  },
  {
    id: "70104",
    number: "7-1D",
    building: "7",
    floor: "1",
    name: "本郷市(3)",
  },
  {
    id: "70105",
    number: "7-1E",
    building: "7",
    floor: "1",
    name: "本郷市(4)",
  },
  {
    id: "70106",
    number: "7-1F",
    building: "7",
    floor: "1",
    name: "本郷市(5)",
  },
  {
    id: "70107",
    number: "7-1G",
    building: "7",
    floor: "1",
    name: "本郷市(6)",
  },
  {
    id: "70108",
    number: "7-1H",
    building: "7",
    floor: "1",
    name: "本郷市(7)",
  },
  {
    id: "70109",
    number: "7-1I",
    building: "7",
    floor: "1",
    name: "本郷市(8)",
  },
  {
    id: "70110",
    number: "7-1J",
    building: "7",
    floor: "1",
    name: "本郷市(9)",
  },
  {
    id: "70111",
    number: "7-1K",
    building: "7",
    floor: "1",
    name: "本郷市(10)",
  },
  {
    id: "70112",
    number: "7-1L",
    building: "7",
    floor: "1",
    name: "本郷市(11)",
  },
  {
    id: "70201",
    number: "7-2A",
    building: "7",
    floor: "2",
    name: "グラウンド",
  },
];
